site_name: Telco Integrator TEST
site_url: https://github.com/IBM/expertise-connect-integration/
site_description: describe asset
theme:
    name: material
    palette:
        primary: 'black'
        accent: 'red'
    font:
        text: 'IBM Plex Sans'
        code: 'IBM Plex Mono'
    features:
        - tabs
        - navigation.tabs
nav:
- HomeTEST: index.md
- Business Case: biz_case.md
- Integrator Solution Overview: solution_overview.md
- Reference Architecture: cloud_app_int_ref-arch.md
- IBM CP4I Capabilites: cp4i-capabilities.md
- TMF Open APIs Integrated: tmf-apis_in_cp4i.md
- Monetize Your APIs: devportal.md
- API Connect Analytics: analytics.md
- Infuse Artificial Intelligence: cp4d-ai.md


# Markdown extensions
markdown_extensions:
    - admonition
    - toc:
        baselevel: 4
        separator: "-"
#       permalink: True
    - sane_lists

# Plugins
plugins:
    - search:
        separator: '[\s\-\.]+'
        prebuild_index: true
#    - macros
  
extra_javascript:
    - js/extra.js 
